version: '3.4'

services:
  dev-image:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/project
    env_file:
      - src/service-variables.env
  worker-image:
    tty: true
    stdin_open: true
    command: bash -c "make && ./avalanche"
    build:
      context: .
      dockerfile: Dockerfile-worker
    env_file:
      - src/service-variables.env
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
