apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker-yaml
spec:
  selector:
    app: worker-yaml
  ports:
    - port: 80
      name: transport
      protocol: TCP
  clusterIP: None